### ISSUE TITLE
About fixup.sh

### ISSUE THREAD

**Issue by grace0x** [arter97/back-to-n0t3#1]
Dear [arter97](https://github.com/arter97),
I want to know how do you generate fixup.sh ?You are special :)

                                                                                           Your admirers

**Comment by arter97** [comment]
I wrote it myself by doing a find, ls, grep -v on the stock firmware.

**Comment by grace0x** [comment]
Wow,Can you make a script and send me. I love it~

**Comment by arter97** [comment]
It's open.
Just use mine and modify yourself based on your needs.

**Comment by grace0x** [comment]
Okay Thanks~
